### ISSUE TITLE
Support display line number, function name, file?

### ISSUE THREAD

**Issue by wolking** [antonfisher/nested-logrus-formatter#2]
```
github.com/sirupsen/logrus v1.4.1
github.com/antonfisher/nested-logrus-formatter v1.0.2
```

I set ReportCaller = true

![image](https://user-images.githubusercontent.com/12195297/57832951-75ddc980-77eb-11e9-8549-aed163fbb97d.png)

But there is no line number, function name, file name。

![image](https://user-images.githubusercontent.com/12195297/57832932-6494bd00-77eb-11e9-9761-04828b0a8131.png)

**Comment by antonfisher** [comment]
Thanks for that, I'll try the option!

**Comment by sankarp-kavach** [comment]
This seem to not work. @wolking @antonfisher Is there something extra that we need to set for this to work ?

**Comment by antonfisher** [comment]
@sankarp-kavach, @wolking Hi, I just released a new version with `logger.SetReportCaller(true)` support, please check out: [v1.0.3](https://github.com/antonfisher/nested-logrus-formatter/releases/tag/v1.0.3). Thanks!
